# サーバーのポート番号
server.port=8000

# SQLiteの接続設定（ドライバ名を修正）
spring.datasource.url=jdbc:sqlite:data/rag_master.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# (任意) データベースがなければ作成する設定
spring.sql.init.mode=always